print("Getting to know you!")
print()
Name = input("What's your name?: ")
Food = input("What's your favourite food?: ")
Music = input("What's your favorite music?: ")
Place = input("Where do you live?: ")
print()
print("You are")
print(Name)
print("You're probably hungry for")
print(Food)
print("and you're definitely getting your froove on to")
print(Music)
print("living in the amazing")
print(Place)
